### ISSUE TITLE
add expires headers to all assets

### ISSUE THREAD

**Issue by adamrneary** [activecell/activecell.com#7]
Expires headers with far future dates will improve performance, but adding the headers is the easy part. The hard part is managing the expired assets. Rails does this by including a digest in the filename and replacing that in the html.

Trade-offs will need to be discussed if we look into this.

**Comment by adamrneary** [comment]
now we're versioning the css and js assets. we should find a way to add far-future expires headers straight away. no more trade-offs!

**Comment by umarsheikh** [comment]
just a comment, i am working on the deploy_update branch, and i cannot start jekyll --server. it looks like you added the lines:

package_assets:     on          # (on, off, always)
embed_assets:       on          # (on, off, datauri)
compress_assets:    on          # (on, off)
gzip_assets:        on          # (on, off)

and now it crashes because embed_assets requires a base_url option, and we neither set it, nor pass it from the jammit_generator.rb plugin. can you run jekyll --server from your copy? i think not, so i will add some defaults and push. you can verify that the base url that i am setting is correct or not.

**Comment by umarsheikh** [comment]
ah! i hadnt pulled! so you got rid of embed_assets, so my changes are not absolutely necessary now. so i removed the baseurl option and pushed again. if later you decide to switch on embed_assets option, it should work correctly.

**Comment by adamrneary** [comment]
Rebase from Master...

On May 11, 2012, at 5:12 AM, umar
reply@reply.github.com
wrote:

**Comment by umarsheikh** [comment]
coming back to this issue: i am exploring how to add far future expires headers to the assets. http://www.cloudcomputingetc.com/2011/07/how-to-add-expires-headers-to-images.html and http://htmlcssjavascript.com/web/setting-far-future-expires-headers-for-images-in-amazon-s3/ suggests there is a manual procedure which involves:
1 logging into the s3 account
2 navigating to the bucket
3 selecting all images css files etc and adding expires headers to them
or
3: use some tool like bucket explorer to select multiple files at once and add expires headers to them

it looks like you can do that since you can log into the account. i am now exploring if there is a programmatic way to accomplish this.

**Comment by adamrneary** [comment]
jekyll-s3 has to have some way to add the header while syncing...

On May 11, 2012, at 7:33 AM, umar
reply@reply.github.com
wrote:

**Comment by adamrneary** [comment]
https://github.com/ebello/Jekyll-S3/blob/master/_libs/aws_s3_sync.rb looks like its got some examples

**Comment by umarsheikh** [comment]
sure, this looks promising

**Comment by adamrneary** [comment]
I believe s3cmd makes syncing only new and changed files easier
(another issue). Might be worth exploring.

On May 11, 2012, at 11:22 AM, umar
reply@reply.github.com
wrote:
