### ISSUE TITLE
deploy should only sync new/modified/deleted assets

### ISSUE THREAD

**Issue by adamrneary** [activecell/activecell.com#8]
Right now it does a complete sync and prompts for deletes. Woof.

**Comment by adamrneary** [comment]
There is an issue in jekyll-s3 about this. https://github.com/versapay/jekyll-s3/pull/7

It would be cleaner if we didn't have to refresh every single asset every time!

**Comment by umarsheikh** [comment]
Now, only the changed files are synced, so the first deploy will take 3 minutes, while the next deploy will finish in 10 seconds if nothing is changed. There is one issue though: i dont think it deletes the files that are deleted, or may be it will ask for deletion, i am not sure, i will have to look into that. so:
- only updates changed files - done
- deletes deleted files, or at least asks to delete deleted files - to check.

In order to run this, install s3cmd command line tool, run s3cmd --configure and enter details, (the access key is our s3_id, and secret_key is the s3_secret in the _jekyll_s3.yml file), check the configuration to make sure it passes, and then deploy with "rake deploy"
